export const PLAYER_ONE_SCORE = "PLAYER_ONE_SCORE";
export const PLAYER_TWO_SCORE = "PLAYER_TWO_SCORE";
export const UPDATE_TEAM_SCORE = "UPDATE_TEAM_SCORE";
export const UPDATE_EXTRAS = "UPDATE_EXTRAS";
